// 天体数据：真实天文参数 + 场景化比例
// 场景比例说明：
//   radius  — 视觉半径，按 sqrt(真实半径比) 压缩，保证大小差异可感知又不失衡
//   dist    — 轨道半径，按 26 + 34·ln(1+AU) 对数压缩，保证行星间距可见
//   periodDays / rotationHours / tiltDeg / inclinationDeg 均为真实值

export const SUN = {
  id: 'sun',
  name: '太阳',
  nameEn: 'Sun',
  radius: 12.5,
  texture: 'sun.jpg',
  desc: '太阳是太阳系的中心恒星，一颗黄矮星（G2V型），占据了太阳系总质量的 99.86%。它的核心每秒将约 6 亿吨氢聚变为氦，释放出的能量维持了地球上几乎所有的生命活动。太阳已经燃烧了约 46 亿年，还将继续燃烧约 50 亿年。',
  stats: {
    '直径': '1,392,700 km（地球的 109 倍）',
    '质量': '1.989 × 10³⁰ kg',
    '表面温度': '约 5,500 °C',
    '核心温度': '约 1,500 万 °C',
    '自转周期': '约 25.4 天（赤道）',
    '年龄': '约 46 亿年',
  },
};

export const PLANETS = [
  {
    id: 'mercury',
    name: '水星',
    nameEn: 'Mercury',
    radius: 0.74,
    dist: 37.2,
    periodDays: 87.97,
    rotationHours: 1407.6,
    tiltDeg: 0.03,
    inclinationDeg: 7.0,
    phase: 0.35,
    texture: 'mercury.jpg',
    desc: '水星是离太阳最近、也是最小的行星。它没有大气层的保护，表面昼夜温差超过 600 °C，是太阳系中温差最大的行星。它的表面布满陨石坑，外观与月球十分相似。',
    stats: {
      '直径': '4,879 km',
      '质量': '3.30 × 10²³ kg',
      '距太阳': '5,790 万 km（0.39 AU）',
      '公转周期': '88 天',
      '自转周期': '58.6 天',
      '表面温度': '-173 °C ~ 427 °C',
      '卫星数': '0',
    },
  },
  {
    id: 'venus',
    name: '金星',
    nameEn: 'Venus',
    radius: 1.17,
    dist: 44.4,
    periodDays: 224.7,
    rotationHours: -5832.5, // 逆行自转
    tiltDeg: 177.4,
    inclinationDeg: 3.4,
    phase: 1.8,
    texture: 'venus.jpg',
    atmosphere: { color: 0xe8c88a, intensity: 0.9 },
    desc: '金星是天空中除日月外最亮的天体，被称为「启明星」或「长庚星」。浓厚的二氧化碳大气层带来了失控的温室效应，使其表面温度高达 464 °C，比水星还热，是太阳系中最炙热的行星。它的自转方向与其他行星相反，且一「天」比一「年」还长。',
    stats: {
      '直径': '12,104 km',
      '质量': '4.87 × 10²⁴ kg',
      '距太阳': '1.08 亿 km（0.72 AU）',
      '公转周期': '224.7 天',
      '自转周期': '243 天（逆行）',
      '表面温度': '约 464 °C',
      '卫星数': '0',
    },
  },
  {
    id: 'earth',
    name: '地球',
    nameEn: 'Earth',
    radius: 1.2,
    dist: 49.5,
    periodDays: 365.25,
    rotationHours: 23.93,
    tiltDeg: 23.44,
    inclinationDeg: 0,
    phase: 3.1,
    texture: 'earth_day.jpg',
    atmosphere: { color: 0x6ab0ff, intensity: 1.0 },
    desc: '地球是目前已知唯一孕育生命的星球。液态水覆盖了约 71% 的表面，氮氧大气层和磁场共同守护着地表的生命。从太空望去，它是一颗悬浮在漆黑宇宙中的蓝色弹珠——我们所有人的家园。',
    stats: {
      '直径': '12,742 km',
      '质量': '5.97 × 10²⁴ kg',
      '距太阳': '1.496 亿 km（1 AU）',
      '公转周期': '365.25 天',
      '自转周期': '23 小时 56 分',
      '表面温度': '平均 15 °C',
      '卫星数': '1（月球）',
    },
  },
  {
    id: 'mars',
    name: '火星',
    nameEn: 'Mars',
    radius: 0.88,
    dist: 57.3,
    periodDays: 686.98,
    rotationHours: 24.62,
    tiltDeg: 25.19,
    inclinationDeg: 1.85,
    phase: 4.6,
    texture: 'mars.jpg',
    atmosphere: { color: 0xd9885a, intensity: 0.45 },
    desc: '火星因表面富含氧化铁而呈现铁锈红色，被称为「红色星球」。这里有太阳系最高的火山——奥林帕斯山（高约 22 km），以及绵延 4,000 km 的水手号峡谷。大量证据表明火星远古时期曾有液态水流淌，它也是人类深空移民的首选目标。',
    stats: {
      '直径': '6,779 km',
      '质量': '6.42 × 10²³ kg',
      '距太阳': '2.28 亿 km（1.52 AU）',
      '公转周期': '687 天',
      '自转周期': '24 小时 37 分',
      '表面温度': '-140 °C ~ 30 °C',
      '卫星数': '2',
    },
  },
  {
    id: 'jupiter',
    name: '木星',
    nameEn: 'Jupiter',
    radius: 3.97,
    dist: 89.0,
    periodDays: 4332.6,
    rotationHours: 9.93,
    tiltDeg: 3.13,
    inclinationDeg: 1.3,
    phase: 0.9,
    texture: 'jupiter.jpg',
    desc: '木星是太阳系中体积和质量最大的行星，其质量是其他七颗行星总和的 2.5 倍。它是一颗气态巨行星，标志性的「大红斑」是一场持续了至少 350 年的巨型风暴，其宽度足以容纳整个地球。木星强大的引力像盾牌一样，替内太阳系挡下了无数彗星和小行星。',
    stats: {
      '直径': '139,820 km',
      '质量': '1.90 × 10²⁷ kg',
      '距太阳': '7.78 亿 km（5.2 AU）',
      '公转周期': '11.86 年',
      '自转周期': '9 小时 56 分',
      '云顶温度': '约 -110 °C',
      '卫星数': '95+',
    },
  },
  {
    id: 'saturn',
    name: '土星',
    nameEn: 'Saturn',
    radius: 3.62,
    dist: 106.3,
    periodDays: 10759,
    rotationHours: 10.7,
    tiltDeg: 26.73,
    inclinationDeg: 2.49,
    phase: 2.4,
    texture: 'saturn.jpg',
    ring: {
      texture: 'saturn_ring.png',
      innerScale: 1.24, // 相对行星半径
      outerScale: 2.27,
    },
    desc: '土星拥有太阳系中最壮观的行星环——由无数冰块和岩石碎屑组成，横跨 28 万 km，厚度却大多只有几十米。土星是一颗气态巨行星，平均密度比水还低，理论上能浮在足够大的水面上。它已确认的卫星数量位居太阳系之首。',
    stats: {
      '直径': '116,460 km',
      '质量': '5.68 × 10²⁶ kg',
      '距太阳': '14.3 亿 km（9.58 AU）',
      '公转周期': '29.46 年',
      '自转周期': '10 小时 42 分',
      '云顶温度': '约 -140 °C',
      '卫星数': '146+',
    },
  },
  {
    id: 'uranus',
    name: '天王星',
    nameEn: 'Uranus',
    radius: 2.39,
    dist: 128.6,
    periodDays: 30687,
    rotationHours: -17.24, // 逆行自转
    tiltDeg: 97.77,
    inclinationDeg: 0.77,
    phase: 5.5,
    texture: 'uranus.jpg',
    desc: '天王星是一颗冰巨行星，大气中的甲烷吸收红光，使它呈现独特的青蓝色。它最奇特之处在于自转轴倾角达 98°——几乎是「躺着」绕太阳滚动，可能源于远古时期一次剧烈的天体撞击。它也是太阳系中大气温度最低的行星。',
    stats: {
      '直径': '50,724 km',
      '质量': '8.68 × 10²⁵ kg',
      '距太阳': '28.7 亿 km（19.2 AU）',
      '公转周期': '84 年',
      '自转周期': '17 小时 14 分（逆行）',
      '云顶温度': '约 -195 °C',
      '卫星数': '28',
    },
  },
  {
    id: 'neptune',
    name: '海王星',
    nameEn: 'Neptune',
    radius: 2.36,
    dist: 143.0,
    periodDays: 60190,
    rotationHours: 16.11,
    tiltDeg: 28.32,
    inclinationDeg: 1.77,
    phase: 1.2,
    texture: 'neptune.jpg',
    desc: '海王星是太阳系最外侧的行星，也是唯一一颗先通过数学计算预言、后被望远镜证实的行星。这颗深蓝色的冰巨行星拥有太阳系中最猛烈的风暴，风速可达 2,100 km/h。它绕太阳一周需要将近 165 个地球年。',
    stats: {
      '直径': '49,244 km',
      '质量': '1.02 × 10²⁶ kg',
      '距太阳': '45 亿 km（30.1 AU）',
      '公转周期': '164.8 年',
      '自转周期': '16 小时 7 分',
      '云顶温度': '约 -200 °C',
      '卫星数': '16',
    },
  },
];

export const MOON = {
  id: 'moon',
  name: '月球',
  nameEn: 'Moon',
  radius: 0.42,
  dist: 3.4, // 相对地球
  periodDays: 27.32,
  rotationHours: 655.7, // 潮汐锁定
  tiltDeg: 6.68,
  inclinationDeg: 5.14,
  phase: 0,
  texture: 'moon.jpg',
  desc: '月球是地球唯一的天然卫星，也是人类唯一登陆过的地外天体。它被潮汐锁定，永远以同一面朝向地球。月球引力驱动着地球的潮汐，并让地球自转轴保持稳定——没有月球，地球的气候将剧烈动荡。',
  stats: {
    '直径': '3,474 km',
    '质量': '7.35 × 10²² kg',
    '距地球': '38.4 万 km',
    '公转周期': '27.3 天',
    '自转周期': '27.3 天（潮汐锁定）',
    '表面温度': '-173 °C ~ 127 °C',
  },
};

// 模拟速度档位：每真实秒对应的模拟天数
export const SPEEDS = [
  { label: '1 时/秒', daysPerSec: 1 / 24 },
  { label: '1 天/秒', daysPerSec: 1 },
  { label: '1 周/秒', daysPerSec: 7 },
  { label: '1 月/秒', daysPerSec: 30 },
  { label: '1 年/秒', daysPerSec: 365 },
];
export const DEFAULT_SPEED_INDEX = 1;
